# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_audit_to_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalallowedkey',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical allowed key'},
        ),
        migrations.AlterModelOptions(
            name='historicalhost',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical host'},
        ),
        migrations.AlterModelOptions(
            name='historicalhostalias',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical host alias'},
        ),
        migrations.AlterModelOptions(
            name='historicalkeyvalue',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical key value'},
        ),
        migrations.AlterModelOptions(
            name='historicallinks',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical links'},
        ),
        migrations.AlterModelOptions(
            name='historicalrestrictedvalue',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical restricted value'},
        ),
        migrations.RemoveField(
            model_name='historicalhostalias',
            name='hostid_id',
        ),
        migrations.RemoveField(
            model_name='historicalkeyvalue',
            name='hostid_id',
        ),
        migrations.RemoveField(
            model_name='historicalkeyvalue',
            name='keyid_id',
        ),
        migrations.RemoveField(
            model_name='historicallinks',
            name='hostid_id',
        ),
        migrations.RemoveField(
            model_name='historicalrestrictedvalue',
            name='keyid_id',
        ),
        migrations.AddField(
            model_name='historicalhostalias',
            name='hostid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='host.Host'),
        ),
        migrations.AddField(
            model_name='historicalkeyvalue',
            name='hostid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='host.Host'),
        ),
        migrations.AddField(
            model_name='historicalkeyvalue',
            name='keyid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='host.AllowedKey'),
        ),
        migrations.AddField(
            model_name='historicallinks',
            name='hostid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='host.Host'),
        ),
        migrations.AddField(
            model_name='historicalrestrictedvalue',
            name='keyid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='host.AllowedKey'),
        ),
        migrations.AlterField(
            model_name='historicalallowedkey',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalhost',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalhostalias',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalkeyvalue',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicallinks',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalrestrictedvalue',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hostalias',
            name='hostid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='host.Host'),
        ),
        migrations.AlterField(
            model_name='links',
            name='hostid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='host.Host'),
        ),
    ]
