#!/usr/bin/env python
# Convert a key to a numeric

import sys
import os
import django

os.environ['DJANGO_SETTINGS_MODULE'] = 'hostinfo.settings'
django.setup()

from host.models import AllowedKey, KeyValue


##############################################################################
def main():
    key = AllowedKey.objects.get(key=sys.argv[1])
    key.numericFlag = True
    key.save()

    kvs = KeyValue.objects.filter(keyid=key)
    print("Converting %d values" % len(kvs))
    for kv in kvs:
        kv.save()


##############################################################################
if __name__ == "__main__":
    main()

# EOF
